version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
  jira: circleci/jira@1.3.0
jobs:
  build_and_deploy:
    working_directory: ~/aus-ddr-poc
    docker:
      - image: cimg/node:17.3.1
    resource_class: medium
    steps:
      - checkout
      - attach_workspace:
          at: ~/aus-ddr-poc
      - run:
          name: install
          command: yarn install
      - run:
          name: Populate .env.$NODE_ENV
          command: |
            printf "CLIENT_ID=$CLIENT_ID\r\n" >> .env.$NODE_ENV
            printf "PROVIDER=$PROVIDER\r\n" >> .env.$NODE_ENV
            printf "API_BASE=$API_BASE\r\n" >> .env.$NODE_ENV
            printf "API_URL=$API_URL\r\n" >> .env.$NODE_ENV
            printf "AUDIENCE=$AUDIENCE\r\n" >> .env.$NODE_ENV
            printf "ASSETS_URL=$ASSETS_URL\r\n" >> .env.$NODE_ENV
      - run: yarn build:prod
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - attach_workspace:
          at: ~/
      - run: echo ${ENVIRONMENT}
      - run: |
          cdn_stack=$(aws ssm get-parameter --name "/${ENVIRONMENT}/webapp/id" | jq -r '.Parameter.Value')
          root_bucket_name=$(aws cloudformation describe-stacks --stack-name "$cdn_stack" | jq -r ".Stacks[0].Outputs[] | select(.ExportName == \"${WEBAPP_BUCKET_EXPORT}\") | .OutputValue")
          root_cdn_id=$(aws cloudformation describe-stacks --stack-name "$cdn_stack" | jq -r ".Stacks[0].Outputs[] | select(.ExportName == \"${WEBAPP_PROXY_EXPORT}\") | .OutputValue")
          aws s3 cp ./dist s3://$root_bucket_name/ --recursive
          aws cloudfront create-invalidation \
            --distribution-id $root_cdn_id \
            --paths "/index.html"
          aws s3 sync ./dist s3://$root_bucket_name/

workflows:
  build_and_test:
    jobs:
      - build_and_deploy:
          name: deploy-staging
          context:
            - staging
          post-steps:
            - jira/notify
          filters:
            branches:
              only: master

      - block_production:
          type: approval
          requires:
            - deploy-staging

      - build_and_deploy:
          name: deploy-production
          context:
            - production
          post-steps:
            - jira/notify
          requires:
            - block_production
          filters:
            branches:
              only: master
