version: 2.1
orbs:
  jira: circleci/jira@1.3.0
  build-tools: circleci/build-tools@2.7.1
jobs:
  install:
    working_directory: ~/aus-ddr-poc
    docker:
      - image: cimg/node:15.6.0
    resource_class: small
    steps:
      - checkout
      - build-tools/merge-with-parent:
          parent: master
      - attach_workspace:
          at: ~/aus-ddr-poc
      - run:
          name: install
          command: yarn install
      - persist_to_workspace:
          root: ~/aus-ddr-poc
          paths: .
  lint:
    working_directory: ~/aus-ddr-poc
    docker:
      - image: cimg/node:15.6.0
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/aus-ddr-poc
      - run: yarn lint
  test:
    working_directory: ~/aus-ddr-poc
    docker:
      - image: cimg/node:15.6.0
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/aus-ddr-poc
      - run: yarn test
  deploy:
    working_directory: ~/aus-ddr-poc
    docker:
      - image: cimg/node:15.6.0
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/aus-ddr-poc
      - run: npm install -g firebase-tools
      - run: firebase deploy --token $FIREBASE_TOKEN_STAGING

workflows:
  build_and_test:
    jobs:
      - install
      - lint:
          post-steps:
            - jira/notify
          requires:
            - install
      - test:
          post-steps:
            - jira/notify
          requires:
            - install

  deploy_staging:
    jobs:
      - install
      - test:
          requires:
            - install
      - deploy:
          post-steps:
            - jira/notify
          requires:
            - test