version: 2.1
orbs:
  jira: circleci/jira@1.3.0
jobs:
  install:
    working_directory: ~/aus-ddr-poc
    docker:
      - image: cimg/node:15.6.0
    resource_class: medium
    steps:
      - checkout
      - attach_workspace:
          at: ~/aus-ddr-poc
      - run:
          name: install
          command: yarn install
      - persist_to_workspace:
          root: ~/
          paths:
            - aus-ddr-poc
  lint:
    working_directory: ~/aus-ddr-poc
    docker:
      - image: cimg/node:15.6.0
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn lint
  test:
    working_directory: ~/aus-ddr-poc
    docker:
      - image: cimg/node:15.6.0
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn test
  build:
    working_directory: ~/aus-ddr-poc
    docker:
      - image: cimg/node:15.6.0
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Populate .env.$NODE_ENV
          command: |
            printf "FIREBASE_API_KEY=$FIREBASE_API_KEY\r\n" >> .env.$NODE_ENV
            printf "FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN\r\n" >> .env.$NODE_ENV
            printf "FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID\r\n" >> .env.$NODE_ENV
            printf "FIREBASE_MESSAGE_SENDER_ID=$FIREBASE_MESSAGE_SENDER_ID\r\n" >> .env.$NODE_ENV
            printf "FIREBASE_APP_ID=$FIREBASE_APP_ID\r\n" >> .env.$NODE_ENV
            printf "FIREBASE_MEASUREMENT_ID=$FIREBASE_MEASUREMENT_ID\r\n" >> .env.$NODE_ENV
            printf "API_URL=$API_URL\r\n" >> .env.$NODE_ENV
            printf "ASSETS_URL=$ASSETS_URL\r\n" >> .env.$NODE_ENV
            printf "BASE_URL=BASE_URL\r\n" >> .env.$NODE_ENV
      - run: yarn build:prod
      - persist_to_workspace:
          root: ~/
          paths:
            - aus-ddr-poc/dist
  deploy_dev:
    working_directory: ~/aus-ddr-poc
    docker:
      - image: cimg/node:15.6.0
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn firebase hosting:channel:deploy ausddrevents-development --token $FIREBASE_TOKEN
  deploy:
    working_directory: ~/aus-ddr-poc
    docker:
      - image: cimg/node:15.6.0
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn firebase hosting:channel:deploy ausddrevents-staging --token $FIREBASE_TOKEN
  deploy_prod:
    working_directory: ~/aus-ddr-poc
    docker:
      - image: cimg/node:15.6.0
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn firebase deploy --token $FIREBASE_TOKEN

workflows:
  build_and_test:
    jobs:
      - install

      - lint:
          post-steps:
            - jira/notify
          requires:
            - install

      - test:
          post-steps:
            - jira/notify
          requires:
            - install

      - build:
          name: build-development
          context:
            - staging
          post-steps:
            - jira/notify
          requires:
            - test
            - lint
          filters:
            branches:
              ignore: master

      - deploy_dev:
          name: deploy-development
          context:
            - staging
          post-steps:
            - jira/notify
          requires:
            - build-development
          filters:
            branches:
              ignore: master

      - build:
          name: build-staging
          context:
            - staging
          post-steps:
            - jira/notify
          requires:
            - test
            - lint
          filters:
            branches:
              only: master

      - deploy:
          name: deploy-staging
          context:
            - staging
          post-steps:
            - jira/notify
          requires:
            - build-staging
          filters:
            branches:
              only: master

      - block_production:
          type: approval
          requires:
            - deploy-staging

      - build:
          name: build-production
          context:
            - production
          post-steps:
            - jira/notify
          requires:
            - block_production
          filters:
            branches:
              only: master

      - deploy_prod:
          context:
            - production
          post-steps:
            - jira/notify
          requires:
            - build-production
          filters:
            branches:
              only: master
