version: 2.1
orbs:
  jira: circleci/jira@1.3.0
  node: circleci/node@4.1.0
jobs:
  install:
    working_directory: ~/aus-ddr-poc
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - checkout
      - attach_workspace:
          at: ~/aus-ddr-poc
      - run:
          name: Install NodeJS 15.8.0
          command: |
            nvm install node
            nvm use node
      - run:
          name: Install Yarn
          command: |
            npm install -g yarn
      - run:
          name: Install dependencies
          command: |
            yarn install
      - persist_to_workspace:
          root: ~/
          paths:
            - aus-ddr-poc
  lint:
    working_directory: ~/aus-ddr-poc
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn lint
  test:
    working_directory: ~/aus-ddr-poc
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn test
  build:
    working_directory: ~/aus-ddr-poc
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Populate .env.$NODE_ENV
          command: |
            printf "FIREBASE_API_KEY=$FIREBASE_API_KEY\r\n" >> .env.$NODE_ENV
            printf "FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN\r\n" >> .env.$NODE_ENV
            printf "FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID\r\n" >> .env.$NODE_ENV
            printf "FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL\r\n" >> .env.$NODE_ENV
            printf "FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET\r\n" >> .env.$NODE_ENV
            printf "FIREBASE_MESSAGE_SENDER_ID=$FIREBASE_MESSAGE_SENDER_ID\r\n" >> .env.$NODE_ENV
            printf "FIREBASE_APP_ID=$FIREBASE_APP_ID\r\n" >> .env.$NODE_ENV
            printf "FIREBASE_MEASUREMENT_ID=$FIREBASE_MEASUREMENT_ID\r\n" >> .env.$NODE_ENV
            printf "API_URL=$API_URL\r\n" >> .env.$NODE_ENV
      - run: yarn build:prod
      - persist_to_workspace:
          root: ~/
          paths:
            - aus-ddr-poc/dist
  deploy:
    working_directory: ~/aus-ddr-poc
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn firebase hosting:channel:deploy ausddrevents-staging --token $FIREBASE_TOKEN

workflows:
  build_and_test:
    jobs:
      - install

      - lint:
          post-steps:
            - jira/notify
          requires:
            - install

      - test:
          post-steps:
            - jira/notify
          requires:
            - install

      - build:
          context:
            - production
          post-steps:
            - jira/notify
          requires:
            - test
            - lint
          filters:
            branches:
              only: master

      - deploy:
          context:
            - production
          post-steps:
            - jira/notify
          requires:
            - build
          filters:
            branches:
              only: master
