version: 2.1
orbs:
  jira: circleci/jira@1.3.0
  build-tools: circleci/build-tools@2.7.1
jobs:
  install:
    working_directory: ~/aus-ddr-poc
    docker:
      - image: cimg/node:15.6.0
    resource_class: small
    steps:
      - checkout
      - build-tools/merge-with-parent:
          parent: master
      - attach_workspace:
          at: ~/aus-ddr-poc
      - run:
          name: install
          command: yarn install
      - persist_to_workspace:
          root: ~/aus-ddr-poc
          paths: .
  lint:
    working_directory: ~/aus-ddr-poc
    docker:
      - image: cimg/node:15.6.0
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/aus-ddr-poc
      - run: yarn lint
  test:
    working_directory: ~/aus-ddr-poc
    docker:
      - image: cimg/node:15.6.0
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/aus-ddr-poc
      - run: yarn test
  deploy_staging:
    working_directory: ~/aus-ddr-poc
    docker:
      - image: cimg/node:15.6.0
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/aus-ddr-poc
      - run:
          name: Populate .env.$NODE_ENV
          command: |
            printf "FIREBASE_API_KEY=$FIREBASE_API_KEY\r\n" >> .env.$NODE_ENV
            printf "FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN\r\n" >> .env.$NODE_ENV
            printf "FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID\r\n" >> .env.$NODE_ENV
            printf "FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL\r\n" >> .env.$NODE_ENV
            printf "FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET\r\n" >> .env.$NODE_ENV
            printf "FIREBASE_MESSAGE_SENDER_ID=$FIREBASE_MESSAGE_SENDER_ID\r\n" >> .env.$NODE_ENV
            printf "FIREBASE_APP_ID=$FIREBASE_APP_ID\r\n" >> .env.$NODE_ENV
            printf "FIREBASE_MEASUREMENT_ID=$FIREBASE_MEASUREMENT_ID\r\n" >> .env.$NODE_ENV
      - run: yarn add firebase-tools
      - run: yarn build:prod
      - run: yarn firebase hosting:channel:deploy ausddrevents-staging --token $FIREBASE_TOKEN

workflows:
  build_and_test:
    jobs:
      - install
      - lint:
          post-steps:
            - jira/notify
          requires:
            - install
      - test:
          post-steps:
            - jira/notify
          requires:
            - install
      - deploy_staging:
          context:
            - aus-ddr-events-staging
          post-steps:
            - jira/notify
          requires:
            - test
          filters:
            branches:
              only: master